### ISSUE TITLE
Decoding a List<int>

### ISSUE THREAD

**Issue by cgarciae** [luizmineo/redstone_mapper#7]
I am trying to decode a list of integers, e.g. "[1,2,3,4]", like this

```
decodeJson(json, new List<int>().runtimeType)
```
but I am getting this error
```
MapperException:  UnsupportedType: List<int>. This type wasn't mapped by redstone_mapper's transformer. See http://goo.gl/YYMou2 for more information.
```
What should I do?

**Comment by cgarciae** [comment]
@luizmineo 
I continued what I was doing since this post, and now I use
```
decodeJson(json, int)
```
as you suggest but now I get this error
```
MapperException:  UnsupportedType: int. This type wasn't mapped by redstone_mapper's transformer. See http://goo.gl/YYMou2 for more information.

STACKTRACE:
#0      _getOrCreateMapper (package:redstone_mapper/mapper_factory_static.dart:234:9)
#1      _TypeDecoder.convert (package:redstone_mapper/src/mapper_impl.dart:31:35)
#2      GenericTypeCodec.decode (package:redstone_mapper/mapper.dart:321:28)
#3      decodeJson (package:redstone_mapper/mapper.dart:68:26)
...
```
which again has to do with the mapper. It seems `int` wasn't registered in the mapper.

BTW: this is client code.

**Comment by luizmineo** [comment]
Ok, I'll take a better look later. Meanwhile, you can decode a List<int> with the JSON codec from `dart:convert`

```dart
JSON.decode("[1, 2, 3, 4]");
```
